apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: kubernetes-intro
spec:
  title: Kubernetes Intro
  description: Kubernetes Intro
  vendor: eduk8s.io
  difficulty: beginner
  duration: 3h
  content:
    #image: quay.io/eduk8s/lab-markdown-sample:master
    files: github.com/jeffellin/LC-K8s-Workshop?ref=main
  session:
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-workshop-user
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-workshop-user
      subjects:
      - kind: ServiceAccount
        namespace: $(workshop_namespace)
        name: $(service_account)
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      docker:
        enabled: true
